from collections import Counter
import json

lista_cruda = [
    "CANNELE", "CANNELE", "CANNELE", "CANNELE", "CANNELE", "CANNELE", "CANNELE", "CANNELE",
    "CARROT CAKE", "CARROT CAKE", "CARROT CAKE", "CARROT CAKE", "CARROT CAKE", "CARROT CAKE", "CARROT CAKE",
    "CHEESE CAKE MARACUYA", "CHEESE CAKE MARACUYA", "CHEESE CAKE MARACUYA", "CHEESE CAKE MARACUYA", "CHEESE CAKE MARACUYA", "CHEESE CAKE MARACUYA", "CHEESE CAKE MARACUYA",
    "CHIPA DE QUESO ( SIN TACC)", "CHIPA DE QUESO ( SIN TACC)", "CHIPA DE QUESO ( SIN TACC)", "CHIPA DE QUESO ( SIN TACC)", "CHIPA DE QUESO ( SIN TACC)", "CHIPA DE QUESO ( SIN TACC)", "CHIPA DE QUESO ( SIN TACC)",
    "CIABATTA", "CIABATTA", "CIABATTA", "CIABATTA", "CIABATTA", "CIABATTA", "CIABATTA", "CIABATTA",
    "COOKIE", "COOKIE", "COOKIE", "COOKIE", "COOKIE", "COOKIE", "COOKIE",
    "COOKIE DE PISTACHO", "COOKIE DE PISTACHO", "COOKIE DE PISTACHO", "COOKIE DE PISTACHO", "COOKIE DE PISTACHO", "COOKIE DE PISTACHO", "COOKIE DE PISTACHO", "COOKIE DE PISTACHO",
    "CROISSANT", "CROISSANT", "CROISSANT", "CROISSANT", "CROISSANT", "CROISSANT", "CROISSANT",
    "CROISSANT DE ALMENDRAS", "CROISSANT DE ALMENDRAS", "CROISSANT DE ALMENDRAS", "CROISSANT DE ALMENDRAS", "CROISSANT DE ALMENDRAS", "CROISSANT DE ALMENDRAS", "CROISSANT DE ALMENDRAS", "CROISSANT DE ALMENDRAS",
    "CROISSANT DE NUTELLA", "CROISSANT DE NUTELLA", "CROISSANT DE NUTELLA", "CROISSANT DE NUTELLA", "CROISSANT DE NUTELLA", "CROISSANT DE NUTELLA", "CROISSANT DE NUTELLA", "CROISSANT DE NUTELLA",
    "CROISSANT DE PISTACHOS", "CROISSANT DE PISTACHOS", "CROISSANT DE PISTACHOS", "CROISSANT DE PISTACHOS", "CROISSANT DE PISTACHOS", "CROISSANT DE PISTACHOS", "CROISSANT DE PISTACHOS", "CROISSANT DE PISTACHOS",
    "CRUMBLE DE MANZANA", "CRUMBLE DE MANZANA", "CRUMBLE DE MANZANA", "CRUMBLE DE MANZANA", "CRUMBLE DE MANZANA", "CRUMBLE DE MANZANA", "CRUMBLE DE MANZANA",
    "DANESA DE CREMA PASTELERA Y FRUTOS ROJOS",
    "ECLAIR DE CHOCOLATE", "ECLAIR DE CHOCOLATE", "ECLAIR DE CHOCOLATE", "ECLAIR DE CHOCOLATE", "ECLAIR DE CHOCOLATE", "ECLAIR DE CHOCOLATE", "ECLAIR DE CHOCOLATE",
    "ECLAIR DE DDL PARIS- BUENOS AIRES", "ECLAIR DE DDL PARIS- BUENOS AIRES", "ECLAIR DE DDL PARIS- BUENOS AIRES", "ECLAIR DE DDL PARIS- BUENOS AIRES", "ECLAIR DE DDL PARIS- BUENOS AIRES", "ECLAIR DE DDL PARIS- BUENOS AIRES", "ECLAIR DE DDL PARIS- BUENOS AIRES",
    "ECLAIR DE PISTACHO", "ECLAIR DE PISTACHO", "ECLAIR DE PISTACHO", "ECLAIR DE PISTACHO", "ECLAIR DE PISTACHO", "ECLAIR DE PISTACHO", "ECLAIR DE PISTACHO", "ECLAIR DE PISTACHO",
    "KOUIGN AMANN", "KOUIGN AMANN", "KOUIGN AMANN", "KOUIGN AMANN", "KOUIGN AMANN", "KOUIGN AMANN", "KOUIGN AMANN",
    "LEMON PIE", "LEMON PIE", "LEMON PIE", "LEMON PIE", "LEMON PIE", "LEMON PIE", "LEMON PIE", "LEMON PIE",
    "MEDIALUNA DE GRASA", "MEDIALUNA DE GRASA", "MEDIALUNA DE GRASA", "MEDIALUNA DE GRASA", "MEDIALUNA DE GRASA", "MEDIALUNA DE GRASA", "MEDIALUNA DE GRASA", "MEDIALUNA DE GRASA",
    "MEDIALUNA DE MANTECA", "MEDIALUNA DE MANTECA", "MEDIALUNA DE MANTECA", "MEDIALUNA DE MANTECA", "MEDIALUNA DE MANTECA", "MEDIALUNA DE MANTECA", "MEDIALUNA DE MANTECA", "MEDIALUNA DE MANTECA",
    "MINI CANNELE", "MINI CANNELE", "MINI CANNELE", "MINI CANNELE", "MINI CANNELE", "MINI CANNELE", "MINI CANNELE",
    "MOÑO DE FRUTOS ROJOS", "MOÑO DE FRUTOS ROJOS", "MOÑO DE FRUTOS ROJOS", "MOÑO DE FRUTOS ROJOS", "MOÑO DE FRUTOS ROJOS", "MOÑO DE FRUTOS ROJOS", "MOÑO DE FRUTOS ROJOS",
    "PALITO DE PARMEGIANO", "PALITO DE PARMEGIANO",
    "PAN DE CHOCOLATE", "PAN DE CHOCOLATE", "PAN DE CHOCOLATE", "PAN DE CHOCOLATE", "PAN DE CHOCOLATE", "PAN DE CHOCOLATE", "PAN DE CHOCOLATE", "PAN DE CHOCOLATE",
    "PAN DE HAMBURGUESA",
    "PAN DE MOLDE", "PAN DE MOLDE", "PAN DE MOLDE", "PAN DE MOLDE", "PAN DE MOLDE", "PAN DE MOLDE", "PAN DE MOLDE",
    "PAN DE MOLDE SEMILLAS", "PAN DE MOLDE SEMILLAS", "PAN DE MOLDE SEMILLAS", "PAN DE MOLDE SEMILLAS", "PAN DE MOLDE SEMILLAS", "PAN DE MOLDE SEMILLAS", "PAN DE MOLDE SEMILLAS", "PAN DE MOLDE SEMILLAS",
    "PAN INTEGRAL 500 GR.", "PAN INTEGRAL 500 GR.", "PAN INTEGRAL 500 GR.", "PAN INTEGRAL 500 GR.", "PAN INTEGRAL 500 GR.", "PAN INTEGRAL 500 GR.", "PAN INTEGRAL 500 GR.", "PAN INTEGRAL 500 GR.",
    "PAN INTEGRAL DE 1 KG.", "PAN INTEGRAL DE 1 KG.", "PAN INTEGRAL DE 1 KG.", "PAN INTEGRAL DE 1 KG.", "PAN INTEGRAL DE 1 KG.", "PAN INTEGRAL DE 1 KG.", "PAN INTEGRAL DE 1 KG.",
    "PAN SEMILLAS 500 GR.", "PAN SEMILLAS 500 GR.", "PAN SEMILLAS 500 GR.", "PAN SEMILLAS 500 GR.", "PAN SEMILLAS 500 GR.", "PAN SEMILLAS 500 GR.", "PAN SEMILLAS 500 GR.",
    "PAN SUIZO", "PAN SUIZO", "PAN SUIZO", "PAN SUIZO", "PAN SUIZO", "PAN SUIZO", "PAN SUIZO", "PAN SUIZO",
    "ROLL DE CANELA", "ROLL DE CANELA", "ROLL DE CANELA", "ROLL DE CANELA", "ROLL DE CANELA", "ROLL DE CANELA", "ROLL DE CANELA", "ROLL DE CANELA",
    "ROLL QUESO AZUL Y NUEZ", "ROLL QUESO AZUL Y NUEZ", "ROLL QUESO AZUL Y NUEZ",
    "SCON DE QUESO", "SCON DE QUESO", "SCON DE QUESO", "SCON DE QUESO", "SCON DE QUESO", "SCON DE QUESO", "SCON DE QUESO", "SCON DE QUESO",
    "TRADITION 1KG", "TRADITION 1KG", "TRADITION 1KG", "TRADITION 1KG", "TRADITION 1KG", "TRADITION 1KG", "TRADITION 1KG",
    "TRADITION 500 GR.", "TRADITION 500 GR.", "TRADITION 500 GR.", "TRADITION 500 GR.", "TRADITION 500 GR.", "TRADITION 500 GR.", "TRADITION 500 GR.",
    "TRADITION BAGUETTE 330 GR.", "TRADITION BAGUETTE 330 GR.", "TRADITION BAGUETTE 330 GR.", "TRADITION BAGUETTE 330 GR.", "TRADITION BAGUETTE 330 GR.", "TRADITION BAGUETTE 330 GR.", "TRADITION BAGUETTE 330 GR."
]

conteo_productos = Counter(lista_cruda)

productos_unicos = []
for nombre, cantidad in sorted(conteo_productos.items()):
    productos_unicos.append({
        "nombre": nombre,
        "cantidad_registros": cantidad,
        "precio_compra": 0.0,
        "porcentaje_merma": 0.05,
        "precio_venta_con_iva": 0.0,
        "alicuota_iva": 0.21
    })

estructura_final = {"productos": productos_unicos}

with open("productos.json", "w", encoding="utf-8") as f:
    json.dump(estructura_final, f, ensure_ascii=False, indent=4)

print("¡Archivo productos.json generado con éxito!")